#!/bin/sh
# v11.11.08

function CemossheInfo () {
    CemossheVerShow
    HostNotesShow
    IsVirtualShow
    SysInfoShow  
    DateShow     
    UptimeShow   
    UnameShow    
    WShow
    DfShow
    FreeShow
    IfconfigShow
    PublicIPShow
    SSHShow
    PstreeShow
    RouteShow 
    LastLoginShow
    NetstatShow  
    FileShow /etc/issue /etc/hosts /etc/resolv.conf
    PackagesShow
    LspciShow   
    LshwShow    
}
