#!/bin/sh

# set -x 

#=========================================================
#=========================================================
# our configuration
#=========================================================
#=========================================================

# Defaults are set in function.cemosshe
SYSTEMNAME=;
SYSTEMGROUP=;
CEMOSSHEDIR=;
DATADIR=;
TEMPDIR=/tmp

NETWAIT=5	# seconds timeout for network service check


#=========================================================
# Startup
#=========================================================
. $CEMOSSHEDIR/functions.cemosshe

MossheSelfCheck $0
MossheInstall

PROPERTYGROUP="System Info"
MossheInfo

#=========================================================
# local checks
#=========================================================

PROPERTYGROUP="Tests"
ForceStatus TestOK OK
ForceStatus TestWARN WARN
ForceStatus TestALERT ALERT

PROPERTYGROUP="Snapshots"
SnapshotsCheck /backup/snapshots 2 5 2 5     # Code fqdn lastrunwarn lastrunalert lastokwarn lastokalert

PROPERTYGROUP="System Checks"
HostsFileCheck
DynamicIPCheck
DaysUpCheck 10 3	# days up less than: warn / alert (days)

UbuntuUpdatesAvailable	# no parameters
UbuntuReleaseUpgrade	# no parameters
UbuntuRebootRequired	# no parameters

HDCheck /dev/mapper/snapshots-root 1000 500	# system disk: 1GB /  500MB  - warn / alert (MByte)

LoadCheck 1 3		# load: warn / alert
MemCheck 300 100	# free mem: warn / alert (MByte)
#SwapCheck 30 100	# page swaps / second : warn / alert

ProcessCheck 120 200	# processes: warn / alert
ZombieCheck 3 10	# zombies: warn / alert
ShellCheck 0 3		# shells: max.root, max.user

NetworkErrorsCheck eth0  1 5		# percentage of errors on interface
NetworkTrafficCheck eth0  50000 80000	# kbit/s average

# check "sensors" output for matching strings on your hardware 
# (second parameter MUST NOT contain space characters)
#HardwareSensor "CHASSIS FAN Speed" Chassis_Fan_Description 6500 7500
#HardwareSensor "CPU Temperature" CPU_Temp_descriptive_text 45 60

# check ClamAV-Daemon which likes to crash
#FileCheck /var/run/clamav/clamd.ctl
#ProcCheck /usr/sbin/clamd

# files growing too old or large
FileTooOld /var/log/syslog 90		# file older than 90 minutes
# FileTooOld /var/log/backup.log 1500	# file older than 90 minutes
#FileTooOld /backup/mysql.sql 86400     # Last mysqldump MySQL backup older than 1 day
#FileTooOld /backup/ldap.ldif 86400     # Last ldapsearch or slapcat LDAP backup older than 1 day
#
#FileTooBig /var/log/auth 9000 	# file bigger than 9,000 KBytes (= 9 MB)
FileTooBig /var/log/syslog 9000 # file bigger than 9,000 KBytes (= 9 MB)

#MailqCheck 20 60

PROPERTYGROUP="IDS"
#LogEntryCheck HTTPbruteforce	' 401 ' '/var/log/apache/*access.log' 100 200		# make sure we don't get HTTP bruteforced
#LogEntryCheck HTTPbruteforce	' 401 ' '/var/log/lighttpd/*access.log' 700 1000		# make sure we don't get HTTP bruteforced
#LogEntryCheck ImapBruteforce	'authdaemond: pam_unix(imap:auth): authentication failure' /var/log/auth.log 10 50     	# we don't like IMAP/Webmail bruteforcing either
#LogEntryCheck Pop3Bruteforce	'authdaemond: pam_unix(pop3:auth): authentication failure' /var/log/auth.log 10 50     	# we don't like IMAP/Webmail bruteforcing either
#LogEntryCheck VsFtpdBruteforce	'pam_unix(vsftpd:auth): authentication failure' /var/log/auth.log 50 100		# we don't like FTP bruteforcing either

LogEntryCheck TooManySU		'Successful su for ' /var/log/auth.log 50 100		# too many SU changes
LogEntryCheck SuFailed		'FAILED su for' /var/log/auth.log 5 10			# SU should not fail too often

LogEntryCheck SSHlogin		'Accepted publickey for ' /var/log/auth.log 100 200	# suspiciously many SSH logins
LogEntryCheck SSHbruteforce	'Illegal user ' /var/log/auth.log 3 5			# we don't like SSH bruteforcing

LogEntryCheck OtherBruteforce	'authentication failure' /var/log/auth.log 50 100	# we don't like other (PAM-based) bruteforcing either
#LogEntryCheck SASLusage		'sasl_username' /var/log/mail.log 400 600		# we don't like SMTP-Auth bruteforcing either

# CheckFileChanges  KnownFile stored in $DATADIR/CompareFiles  OriginalFile
CheckFileChanges resolv.conf /etc/resolv.conf
CheckFileChanges hosts /etc/hosts
CheckFileChanges passwd /etc/passwd
CheckFileChanges shadow /etc/shadow
CheckFileChanges group /etc/group 
CheckFileChanges sudoers /etc/sudoers
CheckFileChanges nsswitch.conf /etc/nsswitch.conf
CheckFileChanges authorized_keys /root/.ssh/authorized_keys

# CheckConfigChanges KnownOutputFile stored in $DATADIR/CompareFiles  "command +parameters"
CheckConfigChanges ifconfig.txt "ifconfig | egrep -v -e 'packets|bytes|collisions'"
CheckConfigChanges routing.txt "netstat -nr"
CheckConfigChanges listeners.txt "netstat -tulpen"

#=========================================================
# Final steps
#=========================================================

Finalize

LogTo /var/log/cemosshe/cemosshe_log Weekly		# continuously log to filename, week is appended automatically

#PushResults sftp cemosshe.cogent-it.com
# You can push to cemosshe.cogent-it.com, but you may not want to
#PushResults curl http://cemosshe.cogent-it.com password

# Always make this the last step
rm -f $TEMPDIR/tmp.$$.collected.tmp $TEMPDIR/cemosshe_lock.*

#############################################################################
# CeMoSSHe: CEntral MOnitoring in a Simple SHell Environment
#
# Copyright (C) 2003- Volker Tanger
# Copyright (C) 2011- Stefan Adams
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# For bug reports and suggestions or if you just want to talk to me please
# contact me at stefan@cogentinnovators.com
#
# Updates will be available at  http://www.cogent-it.com/software/cemosshe/
# please check there for updates prior to submitting patches!
#
# For list of changes please refer to the HISTORY file. Thanks.
#############################################################################
