#!/bin/bash
# v11.11.08

# set -x 

#=========================================================
#=========================================================
# our configuration
#=========================================================
#=========================================================

# Defaults are set in function.cemosshe
#SYSTEMNAME=
#SYSTEMGROUP=
#CEMOSSHEDIR=
#DATADIR=
#TEMPDIR=
#NETWAIT=	# seconds timeout for network service check

#=========================================================
# Startup
#=========================================================
. `dirname $0`/functions.cemosshe

if [ "$1" == "about" ]; then
    curl -b /var/run/cemosshe/session -c /var/run/cemosshe/session -d sn=$(/bin/hostname -f) -X POST http://velite.cogstonestl.com/about
else
    CemossheRun "$1"	# Supply an alternative configuration file on the command line
fi

#############################################################################
# CeMoSSHe: CEntral MOnitoring in a Simple SHell Environment
#
# Copyright (C) 2003- Volker Tanger
# Copyright (C) 2011- Stefan Adams
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# For bug reports and suggestions or if you just want to talk to me please
# contact me at stefan@cogentinnovators.com
#
# Updates will be available at  http://www.cogent-it.com/software/cemosshe/
# please check there for updates prior to submitting patches!
#
# For list of changes please refer to the HISTORY file. Thanks.
#############################################################################
